charlesscrumy/urls.py
from charlesscrumy import views
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import  LoginView
from django.urls import path, include
app_name = 'charlesscrumy'
urlpatterns = [
    path('', views.index, name='index'),
   path('movegoal/<int:goal_id>/', views.move_goal, name='movegoal'),
    path('addgoal/', views.add_goal, name='addgoal'),
    path('home/', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path("logout/", LogoutView.as_view(), name="logout"),
]

django-charlesscrumy/charlesscrumy/urls.py
from charlesscrumy import views
from django.urls import path, include
app_name = 'charlesscrumy'
urlpatterns = [
    path('', views.index, name='index'),
    path('movegoal/<int:goal_id>/', views.move_goal, name='movegoal'),
    path('addgoal/', views.add_goal, name='addgoal'),
    path('home/', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('charlesscrumy/', include('charlesscrumy.urls', namespace='charlesscrumy')),
    path('websocket/', include('websocket.urls')),
]

charlesscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class GoalStatus(models.Model):
    status_name = models.CharField(max_length = 120)
    class Meta:
        permissions = (
            ("can_move_anywhere", "Can change status to any"),
            ("can_move_except_done", "Can change status to any except done"),
            )
    def __str__(self):
        return self.status_name

class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length= 120)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length = 120)
    moved_by = models.CharField(max_length = 120)
    owner = models.CharField(max_length = 120)
    goal_status = models.ForeignKey(GoalStatus, on_delete = models.PROTECT)
    user = models.ForeignKey(User, related_name= 'maps', on_delete = models.CASCADE)
    class Meta:
        permissions = (
            ("can_create_goal", "Can create a weekly goal"),
            ("can_view_goals", "Can view goals"),
            )
    def __str__(self):
        return self.goal_name



class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length = 120) 
    created_by = models.CharField(max_length = 120)
    moved_from = models.CharField(max_length = 120)
    moved_to = models.CharField(max_length = 120)
    time_of_action = models.TimeField()
    goal = models.ForeignKey(ScrumyGoals, on_delete = models.CASCADE)

    def __str__(self):
        return self.created_by

django-charlesscrumy/charlesscrumy/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class GoalStatus(models.Model):
    status_name = models.CharField(max_length = 120)
    def __str__(self):
        return self.status_name

class ScrumyGoals(models.Model):
    goal_name = models.CharField(max_length= 120)
    goal_id = models.IntegerField()
    created_by = models.CharField(max_length = 120)
    moved_by = models.CharField(max_length = 120)
    owner = models.CharField(max_length = 120)
    goal_status = models.ForeignKey(GoalStatus, on_delete = models.PROTECT)
    user = models.ForeignKey(User, on_delete = models.PROTECT)
    def __str__(self):
        return self.goal_name



class ScrumyHistory(models.Model):
    moved_by = models.CharField(max_length = 120) 
    created_by = models.CharField(max_length = 120)
    moved_from = models.CharField(max_length = 120)
    moved_to = models.CharField(max_length = 120)
    time_of_action = models.TimeField()
    goal = models.ForeignKey(ScrumyGoals, on_delete = models.PROTECT)

    def __str__(self):
        return self.created_by

charlesscrumy/views.py
from django.shortcuts import render, redirect
# Create your views here.
from django.http import HttpResponse
from . import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from . import form
from django.contrib.auth import login
from django.contrib.auth import authenticate
GroupDeveloper = Group.objects.get(name = 'Developer') 
GroupOwner = Group.objects.get(name = 'Owner')
GroupQualityAssurance = Group.objects.get(name = 'Quality Assurance')
GroupAdmin = Group.objects.get(name = 'Admin')
import random
idList = []


#from myapp.models import Book
#from django.contrib.auth.models import Group, Permission
#from django.contrib.contenttypes.models import ContentType content_type = ContentType.objects.get_for_model(Book)
#permission = Permission.objects.create(codename='can_publish',
 #                                      name='Can Publish book',
  #                                     content_type=content_type)
#def index(request): 
   # goal = models.ScrumyGoals.objects.filter(goal_name ="Learn Django")
   # for content in goal:
    ##    html = "<html><body><h4>Goals</h4><ul><li>%s</li></ul></body></html>" %content
    #    return HttpResponse(content)



def index(request): 
     if request.method == 'POST': 
         formView = form.SignupForm(request.POST) 
         if formView.is_valid():
            #post = form.save(commit=False)
            newUser = formView.save(commit = False)
            newUser.set_password(request.POST.get('password'))
            newUser.save()
            GroupDeveloper.user_set.add(newUser)
            return HttpResponse('YOUR ACCOUNT HAS BEEN CREATED SUCCESSFULLY')
     else: 
         formView = form.SignupForm()
         return render(request, 'charlesscrumy/index.html', {'form': formView})


def move_goal(request, goal_id):
    if request.method == 'POST':
        goal = models.ScrumyGoals.objects.get(goal_id = goal_id)
        verify = models.GoalStatus.objects.get(status_name = "Verify Goal")
        done =  models.GoalStatus.objects.get(status_name = "Done Goal")
        if request.user.groups.filter(name__in=[GroupDeveloper]).exists() and goal.created_by != request.user.username or request.user.groups.filter(name__in=[GroupOwner]).exists() and goal.created_by != request.user.username:
            return render(request, 'charlesscrumy/exception.html', {'error': 'Sorry, You can only move the goal you created.'})
        elif request.user.groups.filter(name__in=[GroupDeveloper]).exists() and goal.goal_status == done:
            return render(request, 'charlesscrumy/exception.html', {'error': 'Sorry, as a developer, the Done column is none of your business!'})
        elif request.user.groups.filter(name__in=[GroupDeveloper]).exists() and request.POST.get('frequency') == 'Done Goal':
            return render(request, 'charlesscrumy/exception.html', {'error': 'Sorry, you cannot mark goal\'s status as done.'})
        elif request.user.groups.filter(name__in=[GroupQualityAssurance]).exists() and goal.goal_status != verify and goal.created_by != request.user.username and (request.POST.get('frequency') in ['Done Goal', 'Daily Goal', 'Weekly Goal', 'Verify Goal']):
            return render(request, 'charlesscrumy/exception.html', {'error': 'Sorry, as a Quality Assurer, you can only move goals of other users from Verified to Done columns.'})
        elif request.user.groups.filter(name__in=[GroupQualityAssurance]).exists() and goal.goal_status == verify and goal.created_by != request.user.username and (request.POST.get('frequency') in ['Daily Goal', 'Weekly Goal', 'Verify Goal']):
            return render(request, 'charlesscrumy/exception.html', {'error': 'Sorry, as a Quality Assurer, you can only move goals of other users from Verified to Done columns.'})
        else:  
            goal.goal_status = models.GoalStatus.objects.get(status_name = request.POST.get('frequency'))
            goal.save()
            return redirect("charlesscrumy:home")                      
    else:
        return render(request, 'charlesscrumy/movegoal.html')
   

def add_goal(request):
    if request.method == 'POST': 
        if request.user.groups.filter(name__in=[GroupAdmin]).exists():
            return render(request, 'charlesscrumy/exception.html', {'error': 'Sorry, your job is to move goals to and fro statuses.'})
        ID = []
        i = 0
        while i < len(idList) + 1:
            rnd = random.randint(1000 , 9999)
            if rnd in idList:
                continue
            ID.append(rnd)
            i = i+ 1
        requiredID = ID[0]
        idList.append(requiredID)
    
        models.ScrumyGoals.objects.create(goal_name = request.POST.get('goal_name'), 
                                        goal_id = requiredID,
                                        created_by = request.user.username, 
                                        moved_by = request.user.username,
                                        owner = request.user.username,
                                        goal_status =  models.GoalStatus.objects.get(status_name = "Weekly Goal"), 
                                        user = User.objects.get(username = request.POST.get('user')))
        return redirect("charlesscrumy:home") 
    else:
        if request.user.groups.filter(name__in=[GroupDeveloper, GroupQualityAssurance, GroupOwner]).exists():
            return render(request, 'charlesscrumy/addgoal.html', {'users': User.objects.filter(first_name = request.user.first_name)})
        else:
            return render(request, 'charlesscrumy/addgoal.html', {'users': User.objects.all()})

                
def home(request):
    context = {'users': User.objects.all(), 
                'weeklyGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Weekly Goal")),
                'dailyGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Daily Goal")),
                'verifyGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Verify Goal")),
                'doneGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Done Goal"))}
    
    return render(request, 'charlesscrumy/home.html', context)



    

def logout_request(request):
    logout(request)
    return redirect("charlesscrumy:index")

django-charlesscrumy/charlesscrumy/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse 
from . import models
from django.contrib.auth.models import User

import random
idList = []



def index(request): 
    goal = models.ScrumyGoals.objects.filter(goal_name ="Learn Django")
    for content in goal:
        html = "<html><body><h4>Goals</h4><ul><li>%s</li></ul></body></html>" %content
        return HttpResponse("<html><body><h1>This is a Scrum Application</h1></body></html>\n\n %s" %html)



def move_goal(request, goal_id):
    context = {'error': 'A record with that goal id %d does not exist.' %goal_id}
    try: goal = models.ScrumyGoals.objects.get(goal_id= goal_id) 
    except Exception as e: return render(request, 'charlesscrumy/exception.html', context) 
    else: return HttpResponse(goal.goal_name)

def add_goal(request):
    ID = []
    i = 0
    while i < len(idList):
        rnd = random.randint(1000 , 9999)
        if rnd in idList:
            continue
        ID.append(rnd)
        i = i+ 1
    requiredID = ID[0]
    idList.append(requiredID)
    
    models.ScrumyGoals.objects.create(goal_name = 'Keep Learning Django', 
                                        goal_id = requiredID,
                                        created_by = 'Louis', 
                                        moved_by = 'Louis',
                                        owner = 'Louis',
                                        goal_status =  models.GoalStatus.objects.get(status_name = "Weekly Goal"), 
                                        user = User.objects.get(username = 'louis'))

                
def home(request):
    context = {'users': User.objects.all(), 
                'weeklyGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Weekly Goal")),
                'dailyGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Daily Goal")),
                'verifyGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Verify Goal")),
                'doneGoals': models.ScrumyGoals.objects.filter(goal_status = models.GoalStatus.objects.get(status_name = "Done Goal"))}
    #return HttpResponse("%s" %output)
    return render(request, 'charlesscrumy/home.html', context)


    

charlesscrumy/templates/charlesscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <title>Add Goal</title>
</head>
<body class="ui container">
    {% if user.is_authenticated %}
    <br>
    <div class="field">
       <h4><i class="icon user"></i>{{user.username}}</h4> 
    </div>
    {% endif %}
    <form method="POST" class="ui form segment">
        {% csrf_token%}
        <div class="field">
            <label for="">Goal</label>
            <input type="text" name="goal_name" placeholder="Name of goal">
        </div>
        <div class="field">
            <label for="">Created For:</label>
            <select id="cars" name="user">
                {% for currentUser in users %}
              <option value={{currentUser}}>{{currentUser.first_name}}</option>
                {% endfor %}
            </select>
        </div>
        
        <input type="submit" value="Submit" class="ui submit button primary">
    </form>
    <a href="{% url 'charlesscrumy:home' %}"> Home </a>
   
    
    
</body>
</html>

charlesscrumy/templates/charlesscrumy/exception.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <p>{{error}}</p>
    <p></p>
    <a href="{% url 'charlesscrumy:home' %}">Home</a>
</body>
</html>

charlesscrumy/templates/charlesscrumy/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <title>SCRUM APPLICATION</title>
</head>
<body class="ui container">
    {% if user.is_authenticated %}
    <br>
    <div class="field">
       <h4><i class="icon user"></i>{{user.first_name}}</h4> 
    </div>
    {% endif %}
    <h2 style="text-align: center;">Scrumy Board</h2>
    <table class="ui table">
        <tr  >
            <th style="padding: 12px;">User</th>
            <th>Weekly Goals</th>
            <th>Daily Goals</th>
            <th>Verify Goals</th>
            <th>Done Goals</th>
        </tr>
        {% for currentUser in users %}
        <tr> 
            <td>{{currentUser.first_name}}</td>   
            <td>
                <ul style="padding: 0;">
                    {% for weekly  in currentUser.maps.all %}
                    {% if weekly in weeklyGoals %}
                    <li style="list-style: none">{{ weekly.goal_name }} : {{ weekly.goal_id }} <br>
                      <a style="font-size: 11px;" href="{% url 'charlesscrumy:movegoal' weekly.goal_id %} ">Move goal</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul style="padding: 0;">
                    {% for daily  in currentUser.maps.all %}
                    {% if daily in dailyGoals %}
                    <li style="list-style: none">{{ daily.goal_name }} : {{ daily.goal_id }} <br>
                       <a style="font-size: 11px;"  href="{% url 'charlesscrumy:movegoal' daily.goal_id %}">Move goal</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul style="padding: 0;">
                    {% for verify  in currentUser.maps.all %}
                    {% if verify  in verifyGoals %}
                    <li style="list-style: none;">{{ verify.goal_name }} : {{ verify.goal_id }} <br>
                        <a style="font-size: 11px;" href="{% url 'charlesscrumy:movegoal' verify.goal_id %} ">Move goal</a>
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </td>
            <td>
                <ul style="padding: 0;">
                    {% for done  in currentUser.maps.all %}
                    {% if done in doneGoals %}
                    <li style="list-style: none">{{ done.goal_name }} : {{ done.goal_id }} <br>
                        <a style="font-size: 11px;"  href="{% url 'charlesscrumy:movegoal' done.goal_id %} ">Move goal</a>
                       
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            </td>
        </tr>
        {% endfor %}
    </table>
    <p><a href="{% url 'charlesscrumy:addgoal'%}">Add goal</a></p>
    {% if user.is_authenticated %}
    <p><a href="{% url 'charlesscrumy:logout'%}">Logout</a></p>
    {% endif %}
</body>
</html>

charlesscrumy/templates/charlesscrumy/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">

    <title>User account</title>
</head>
<body class="ui container">
    {% if user.is_authenticated %}
    <br>
    <div class="field">
       <h4><i class="icon user"></i>{{user.username}}</h4> 
    </div>
    {% endif %}
    <h2>User Account</h2>
    <form method="POST" class="ui form segment">{% csrf_token %}
        {% for field in form%}
        
            <div class="field">
                {{field.errors}}
                {{field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                <sup> {{ field.help_text }}</sup>
                {% endif %}
            </div>
       
        {% endfor %}
        <div class="field">
            <button type="submit" class="ui submit button primary">Sign up</button>
        </div>
        
    </form>
    <a href="{% url 'charlesscrumy:home' %}">Home</a>
</body>
</html>

charlesscrumy/templates/charlesscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <title>Add Goal</title>
</head>
<body class="ui container">
  
    <form method="POST" class="ui form segment" style="margin-top: 50px;">
        {% csrf_token%}
            <div class="inline fields">
              <label>Select the status you wish to the move goal to:</label>
              <div class="field">
                <div class="ui radio checkbox">
                  <input type="radio" name="frequency" checked="checked" value="Weekly Goal">
                  <label>Weekly Goal</label>
                </div>
              </div>
              <div class="field">
                <div class="ui radio checkbox">
                  <input type="radio" name="frequency" value="Daily Goal">
                  <label>Daily Goal</label>
                </div>
              </div>
              <div class="field">
                <div class="ui radio checkbox">
                  <input type="radio" name="frequency" value="Verify Goal">
                  <label>Verify Goal</label>
                </div>
              </div>
              <div class="field">
                <div class="ui radio checkbox">
                  <input type="radio" name="frequency" value="Done Goal">
                  <label>Done Goal</label>
                </div>
              </div>
            </div>
            <div class="field">
                <button type="submit" class="ui submit button primary">Move Goal</button>
            </div>
    </form>
   
</body>
</html>